[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/ping"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[project]
name = "saju-backend"
language = "python"
